a=float(input("Enter value of a:"))
b=float(input("Enter value of b:"))
print("*"*50)
print("\t\tsum({},{})={}".format(a,b,a+b))
print("\t\tsub({},{})={}".format(a,b,a-b))
print("\t\tmul({},{})={}".format(a,b,a*b))
print("\t\tdiv({},{})={}".format(a,b,a/b))
print("\t\tfloordiv({},{})={}".format(a,b,a//b))
print("\t\tmoddiv({},{})={}".format(a,b,a%b))
print("\t\texp({},{})={}".format(a,b,a**b))
print("*"*50)
